### ISSUE TITLE
Custom directory mostly breaks past recording listing, completley breaks playback

### ISSUE THREAD

**Issue by EkriirkE** [SimpleMobileTools/Simple-Voice-Recorder#153]
Android 11
F-Droid voicerecorder 5.10.2

The default location of Internal>Music>Record worked great.  I changed it to Internal>Record, it asked me to confirm "use this folder" via android.settings Files, which I did and selected Allow.  
Interestingly the initial folder choice dialogue from VoiceRecorder shows 0 items when there are hundreds.

When the app is killed/freshly started the Player tab is empty.  Some time later (10+ minutes) it will correctly populate.
Recording works great.  New recordings do not appear in Playback until I force stop VoiceRecorder.  Renaming has a similar effect - the change is not reflected until 
Selecting anything shows a toast of "Error:  java.io.IOException: setDataSource failed.: status=0x80000000" and playback does not work at all.  The duration is correct on the scrubber but nothing happens trying to play back and scrubbing does not move. 
Logat has
```
10-15 19:29:13.512 29942 29942 V MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
10-15 19:29:13.512 29942 29942 V MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
10-15 19:29:13.520 32271  1549 W ActivityManager: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from (null) (pid=32153, uid=1013) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
10-15 19:29:13.521 32153 22200 D mediaserver: openContentUri(content://com.android.externalstorage.documents/tree/primary%3ARecord/document/primary%3ARecord%2F2022_10_04_12_25_52.m4a) caught exception -129
10-15 19:29:13.521 32153 22200 E MediaPlayerService: Couldn't open fd for content://com.android.externalstorage.documents/tree/primary%3ARecord/document/primary%3ARecord%2F2022_10_04_12_25_52.m4a
10-15 19:29:13.521 29942 29942 E MediaPlayerNative: Unable to create media player
```

Deleting items does not work - It shows a prompt to "Allow Voice Recorder to delete this audio file?" and allowing it makes it disappear from the list, but closing and re-opening shows it returned and never deleted.  
Logcat has
```
10-15 20:07:56.261  1636 25283 W MediaProvider: java.io.FileNotFoundException: No item at content://media/external/audio/media/235467876
10-15 20:07:56.261  1636 25283 W MediaProvider: 	at com.android.providers.media.MediaProvider.ensureThumbnail(MediaProvider.java:5908)
10-15 20:07:56.261  1636 25283 W MediaProvider: 	at com.android.providers.media.MediaProvider.openTypedAssetFileCommon(MediaProvider.java:5849)
10-15 20:07:56.261  1636 25283 W MediaProvider: 	at com.android.providers.media.MediaProvider.openTypedAssetFile(MediaProvider.java:5836)
10-15 20:07:56.261  1636 25283 W MediaProvider: 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:553)
10-15 20:07:56.261  1636 25283 W MediaProvider: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1983)
10-15 20:07:56.261  1636 25283 W MediaProvider: 	at android.content.ContentResolver.openTypedAssetFile(ContentResolver.java:1888)
10-15 20:07:56.261  1636 25283 W MediaProvider: 	at android.content.ContentResolver.lambda$loadThumbnail$0(ContentResolver.java:4040)
10-15 20:07:56.261  1636 25283 W MediaProvider: 	at android.content.-$$Lambda$ContentResolver$7ILY1SWNxC2xhk-fQUG6tAXW9Ik.call(Unknown Source:10)
10-15 20:07:56.261  1636 25283 W MediaProvider: 	at android.graphics.ImageDecoder$CallableSource.createImageDecoder(ImageDecoder.java:558)
10-15 20:07:56.261  1636 25283 W MediaProvider: 	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1862)
10-15 20:07:56.261  1636 25283 W MediaProvider: 	at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1855)
10-15 20:07:56.261  1636 25283 W MediaProvider: 	at android.content.ContentResolver.loadThumbnail(ContentResolver.java:4039)
10-15 20:07:56.261  1636 25283 W MediaProvider: 	at android.content.ContentResolver.loadThumbnail(ContentResolver.java:4023)
10-15 20:07:56.261  1636 25283 W MediaProvider: 	at com.android.providers.media.PermissionActivity$Description.<init>(PermissionActivity.java:694)
10-15 20:07:56.261  1636 25283 W MediaProvider: 	at com.android.providers.media.PermissionActivity$DescriptionTask.doInBackground(PermissionActivity.java:531)
10-15 20:07:56.261  1636 25283 W MediaProvider: 	at com.android.providers.media.PermissionActivity$DescriptionTask.doInBackground(PermissionActivity.java:458)
10-15 20:07:56.261  1636 25283 W MediaProvider: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
10-15 20:07:56.261  1636 25283 W MediaProvider: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-15 20:07:56.261  1636 25283 W MediaProvider: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
10-15 20:07:56.261  1636 25283 W MediaProvider: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-15 20:07:56.261  1636 25283 W MediaProvider: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-15 20:07:56.261  1636 25283 W MediaProvider: 	at java.lang.Thread.run(Thread.java:923)
10-15 20:07:56.263  1636 25283 W ContentResolver: Failed to get type for: content://media/external/audio/media/235467876 (No item at content://media/external/audio/media/235467876)
10-15 20:07:56.263  1636 25283 W MediaProvider: java.lang.NullPointerException
10-15 20:07:56.263  1636 25283 W MediaProvider: 	at java.util.Objects.requireNonNull(Objects.java:220)
10-15 20:07:56.263  1636 25283 W MediaProvider: 	at android.content.ContentResolver.getTypeInfo(ContentResolver.java:3858)
10-15 20:07:56.263  1636 25283 W MediaProvider: 	at com.android.providers.media.PermissionActivity$Description.<init>(PermissionActivity.java:711)
10-15 20:07:56.263  1636 25283 W MediaProvider: 	at com.android.providers.media.PermissionActivity$DescriptionTask.doInBackground(PermissionActivity.java:531)
10-15 20:07:56.263  1636 25283 W MediaProvider: 	at com.android.providers.media.PermissionActivity$DescriptionTask.doInBackground(PermissionActivity.java:458)
10-15 20:07:56.263  1636 25283 W MediaProvider: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
10-15 20:07:56.263  1636 25283 W MediaProvider: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-15 20:07:56.263  1636 25283 W MediaProvider: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
10-15 20:07:56.263  1636 25283 W MediaProvider: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-15 20:07:56.263  1636 25283 W MediaProvider: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-15 20:07:56.263  1636 25283 W MediaProvider: 	at java.lang.Thread.run(Thread.java:923)
10-15 20:07:57.072  1636 25283 D MediaProvider: User allowed grant for [content://media/external/audio/media/235467876]
10-15 20:07:57.074  1636 25283 I MediaProvider: Granted permission to 1 items on external to com.simplemobiletools.voicerecorder

```

**Comment by Warden20** [comment]
This happens to me too.
I have the last release 5.11.2
Android 13

**Comment by EkriirkE** [comment]
This reminds me, I also upgraded to Android 13 a month ago and it still does this -- however a recent update a couple weeks ago seems to want to default to the Playback screen which means the app does not load for several minutes, completely frozen and causing android unresponsive "Wait / Close" prompts.  Once it does finally load (sometimes it won't) I can record as usual but all the other issues remain (cannot playback, delete does nothing, rename dosn't reflect for another several minutes, etc)

At this point I can no longer use the app.  (FDroid 5.11.1)
